// <auto-generated />
using System;
using BrunSker.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrunSker.Infra.Migrations
{
    [DbContext(typeof(BrunSkerDbContext))]
    [Migration("20220826001331_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BrunSker.Domain.Entities.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("char(9)")
                        .HasColumnName("cep");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("complemento");

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("ddd");

                    b.Property<string>("Gia")
                        .HasColumnType("char(4)")
                        .HasColumnName("gia");

                    b.Property<string>("Ibge")
                        .IsRequired()
                        .HasColumnType("char(7)")
                        .HasColumnName("ibge");

                    b.Property<int>("LocacaoId")
                        .HasColumnType("int");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("localidade");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("logradouro");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("registration_date");

                    b.Property<string>("Siafi")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .HasColumnName("siafi");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.HasIndex("LocacaoId")
                        .IsUnique();

                    b.ToTable("Endereco", (string)null);
                });

            modelBuilder.Entity("BrunSker.Domain.Entities.Locacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<ulong>("EstaLocado")
                        .HasColumnType("bit(1)")
                        .HasColumnName("esta_locado");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("registration_date");

                    b.HasKey("Id");

                    b.ToTable("Locacao", (string)null);
                });

            modelBuilder.Entity("BrunSker.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("BrunSker.Domain.Entities.Locacao", "Locacao")
                        .WithOne("Endereco")
                        .HasForeignKey("BrunSker.Domain.Entities.Endereco", "LocacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Locacao");
                });

            modelBuilder.Entity("BrunSker.Domain.Entities.Locacao", b =>
                {
                    b.Navigation("Endereco")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
