// <auto-generated />
using System;
using BrunSker.Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BrunSker.Infra.Migrations
{
    [DbContext(typeof(BrunSkerDbContext))]
    partial class BrunSkerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BrunSker.Domain.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("char(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Complemento")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("complemento");

                    b.Property<string>("Ddd")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("ddd");

                    b.Property<string>("Gia")
                        .HasColumnType("char(4)")
                        .HasColumnName("gia");

                    b.Property<string>("Ibge")
                        .IsRequired()
                        .HasColumnType("char(7)")
                        .HasColumnName("ibge");

                    b.Property<string>("Localidade")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("localidade");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("logradouro");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("registration_date");

                    b.Property<string>("Siafi")
                        .IsRequired()
                        .HasColumnType("char(4)")
                        .HasColumnName("siafi");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    b.ToTable("Address", (string)null);
                });

            modelBuilder.Entity("BrunSker.Domain.Entities.Lease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<ulong>("IsRented")
                        .HasColumnType("bit(1)")
                        .HasColumnName("is_rented");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime")
                        .HasColumnName("registration_date");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Lease", (string)null);
                });

            modelBuilder.Entity("BrunSker.Domain.Entities.Lease", b =>
                {
                    b.HasOne("BrunSker.Domain.Entities.Address", "Address")
                        .WithOne("Lease")
                        .HasForeignKey("BrunSker.Domain.Entities.Lease", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("BrunSker.Domain.Entities.Address", b =>
                {
                    b.Navigation("Lease")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
